version: '3'
services:
  app:
    image: ubuntu:latest
    volumes: # マウントするディレクトリ
      - ./app:/app
    command: bash -c "apt-get -y update && apt-get -y install python3 && python3 -m http.server 8000" # docker compose up で実行されるコマンド（良い子はインストールスクリプトをcommandに書かないでね）
    working_dir: /app # 初期配置

  tunnel: # 見て見ぬふりをしてほしい
    restart: unless-stopped
    image: cloudflare/cloudflared
    command: tunnel --url http://app:8000
